# Configurações do servidor
server:
  port: 8081 # Porta específica para o book-service
  servlet:
    context-path: /api/books # Prefixo para os endpoints do serviço

# Nome do serviço (para Service Discovery, se usado)
spring:
  application:
    name: book-service

  # Configurações do banco de dados
  datasource:
    url: jdbc:mariadb://localhost:3306/ASID-Book-Service # Nome do banco de dados específico para o book-service
    username: root
    password: senha
    driver-class-name: org.mariadb.jdbc.Driver

  # Configurações do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Atualiza o esquema do banco automaticamente
    show-sql: true # Exibe as queries SQL no console (opcional)
    properties:
      hibernate:
        format_sql: true # Formata as queries SQL no console (opcional)

# Configurações de logs (opcional)
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG # Mostra as queries SQL no log