server:
  port: 8080

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:mariadb://book-db:3306/bookdb
    username: root
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: book-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
