server:
  port: 8080

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:mariadb://book-db:3306/bookdb
    username: root
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
