apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: MAD.ocir.io/axwj6egh1rpg/book-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          args:
            - "--server.port=8080"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://book-db:3306/bookdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: secret
      imagePullSecrets:
        - name: ocirsecret

---

apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP

