version: '3.8'

services:
  # Service Registry (Eureka)
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  # API Gateway
  gateway-service:
    build:
      context: ./api-gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - backend

  # Book Service
  book-service:
    build:
      context: ./microservices/book-service
    container_name: book-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://book-db:3306/bookdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - book-db
      - eureka-server
    ports:
      - "8081:8080"
    networks:
      - backend

  book-db:
    image: mariadb:10.7
    container_name: book-db
    environment:
      MYSQL_DATABASE: bookdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - bookdb-data:/var/lib/mysql
    networks:
      - backend

  # Cart Service
  cart-service:
    build:
      context: ./microservices/cart-service
    container_name: cart-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://cart-db:3306/cartdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - cart-db
      - eureka-server
    ports:
      - "8082:8080"
    networks:
      - backend

  cart-db:
    image: mariadb:10.7
    container_name: cart-db
    environment:
      MYSQL_DATABASE: cartdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - cartdb-data:/var/lib/mysql
    networks:
      - backend

  # Order Service
  order-service:
    build:
      context: ./microservices/order-service
    container_name: order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://order-db:3306/orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - order-db
      - eureka-server
    ports:
      - "8084:8080"
    networks:
      - backend

  order-db:
    image: mariadb:10.7
    container_name: order-db
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - orderdb-data:/var/lib/mysql
    networks:
      - backend

  # Shipping Service
  shipping-service:
    build:
      context: ./microservices/shipping-service
    container_name: shipping-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://shipping-db:3306/shippingdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - shipping-db
      - eureka-server
    ports:
      - "8085:8080"
    networks:
      - backend

  shipping-db:
    image: mariadb:10.7
    container_name: shipping-db
    environment:
      MYSQL_DATABASE: shippingdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3310:3306"
    volumes:
      - shippingdb-data:/var/lib/mysql
    networks:
      - backend

  user-service:
    build:
      context: ./microservices/user-service
    container_name: user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://user-db:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - user-db
      - eureka-server
    ports:
      - "8086:8080"
    networks:
      - backend


  user-db:
    image: mariadb:10.7
    container_name: user-db
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3311:3306"
    volumes:
      - userdb-data:/var/lib/mysql
    networks:
      - backend


volumes:
  bookdb-data:
  cartdb-data:
  orderdb-data:
  shippingdb-data:
  userdb-data:


networks:
  backend:
