version: '3.8'

services:
  # Zookeeper (necessário para Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - backend

  # Kafka Web UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8088:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - backend

  # API Gateway
  gateway-service:
    build:
      context: ./api-gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - backend

  # Book Service
  book-service:
    build:
      context: ./microservices/book-service
    container_name: book-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://book-db:3306/bookdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - book-db
    ports:
      - "8081:8080"
    networks:
      - backend

  book-db:
    image: mariadb:10.7
    container_name: book-db
    environment:
      MYSQL_DATABASE: bookdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - bookdb-data:/var/lib/mysql
    networks:
      - backend

  # Cart Service
  cart-service:
    build:
      context: ./microservices/cart-service
    container_name: cart-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://cart-db:3306/cartdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - cart-db
    ports:
      - "8082:8080"
    networks:
      - backend

  cart-db:
    image: mariadb:10.7
    container_name: cart-db
    environment:
      MYSQL_DATABASE: cartdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - cartdb-data:/var/lib/mysql
    networks:
      - backend

  # Order Service
  order-service:
    build:
      context: ./microservices/order-service
    container_name: order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://order-db:3306/orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - order-db
      - kafka
    ports:
      - "8084:8080"
    networks:
      - backend

  order-db:
    image: mariadb:10.7
    container_name: order-db
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - orderdb-data:/var/lib/mysql
    networks:
      - backend

  # Shipping Service
  shipping-service:
    build:
      context: ./microservices/shipping-service
    container_name: shipping-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://shipping-db:3306/shippingdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - shipping-db
    ports:
      - "8085:8080"
    networks:
      - backend

  shipping-db:
    image: mariadb:10.7
    container_name: shipping-db
    environment:
      MYSQL_DATABASE: shippingdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3310:3306"
    volumes:
      - shippingdb-data:/var/lib/mysql
    networks:
      - backend

  # User Service
  user-service:
    build:
      context: ./microservices/user-service
    container_name: user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://user-db:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - user-db
    ports:
      - "8086:8080"
    networks:
      - backend

  user-db:
    image: mariadb:10.7
    container_name: user-db
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3311:3306"
    volumes:
      - userdb-data:/var/lib/mysql
    networks:
      - backend

  # Order History Service
  order-history-service:
    build:
      context: ./microservices/order-history-service
    container_name: order-history-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://order-history-db:3306/orderhistory
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - order-history-db
      - kafka
    ports:
      - "8087:8080"
    networks:
      - backend

  order-history-db:
    image: mariadb:10.7
    container_name: order-history-db
    environment:
      MYSQL_DATABASE: orderhistory
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3312:3306"
    volumes:
      - orderhistorydb-data:/var/lib/mysql
    networks:
      - backend

volumes:
  bookdb-data:
  cartdb-data:
  orderdb-data:
  shippingdb-data:
  userdb-data:
  orderhistorydb-data:

networks:
  backend:
