server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://book-service:8080
          predicates:
            - Path=/books/**

        - id: cart-service
          uri: http://cart-service:8080
          predicates:
            - Path=/cart/**

        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/orders/**

        - id: shipping-service
          uri: http://shipping-service:8080
          predicates:
            - Path=/shipping/**

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/auth/**, /users/**
        
        - id: order-history-service
          uri: http://order-history-service:8080
          predicates:
            - Path=/history/**


  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
