
server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=Access-Control-Allow-Origin,*
      routes:
        # - id: auth-service
        #   uri: http://localhost:8081
        #   predicates:
        #     - Path=/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: book-service
          uri: http://localhost:8083
          predicates:
            - Path=/books/**
        # - id: cart-service
        #   uri: http://localhost:8084
        #   predicates:
        #     - Path=/cart/**
        # - id: order-service
        #   uri: http://localhost:8085
        #   predicates:
        #     - Path=/orders/**
        # - id: shipping-service
        #   uri: http://localhost:8086
        #   predicates:
        #     - Path=/shipping/**
