server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
      discovery:
        locator:
          enabled: false

  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
