apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-db
  labels:
    app: book-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-db
  template:
    metadata:
      labels:
        app: book-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "secret"
            - name: MYSQL_DATABASE
              value: "bookdb"
---
apiVersion: v1
kind: Service
metadata:
  name: book-db
spec:
  type: ClusterIP
  selector:
    app: book-db
  ports:
    - port: 3306
      targetPort: 3306

